### ISSUE TITLE
[Feature Request]: Feed notification on fetching error

### ISSUE THREAD

**Issue by StayPirate** [skx/rss2email#119]
It would be nice to get a notification if a feed didn't work, with related details in the notification body. Currently rss2email report all the errors at the end of its output after each run.

```
rss2email_security-feed  | Fetching feed: http://rss-bridge-proxy.home/spotify/show/0av5zTSOSIuBBtOjqjJWFc
rss2email_security-feed  |      Feed contains 1 entries
rss2email_security-feed  |      01 entries already seen
rss2email_security-feed  |      00 entries not seen before
rss2email_security-feed  | Fetching from same host as previous feed, rss-bridge-proxy.home, adding 5s delay
rss2email_security-feed  | Fetching feed: http://rss-bridge-proxy.home/spotify/show/6mdVBCDxhGKuULeca9psdl
rss2email_security-feed  |      Feed contains 1 entries
rss2email_security-feed  |      01 entries already seen
rss2email_security-feed  |      00 entries not seen before
rss2email_security-feed  | error processing https://www.elastic.co/security-labs/feed - 552 5.7.0 This message was blocked because its content presents a potential
rss2email_security-feed  | 5.7.0 security issue. Please visit
rss2email_security-feed  | 5.7.0  https://support.google.com/mail/?p=BlockedMessage to review our
rss2email_security-feed  | 5.7.0 message content and attachment content guidelines. w17-20020a05600c475100b0040b45356b72sm21838070wmo.33 - gsmtp
rss2email_security-feed  | error processing https://trickest.com/blog/index.xml - error parsing https://trickest.com/blog/index.xml contents: Failed to detect feed type <!DOCTYPE html>
```

The problem I see here is that a user only becomes aware of broken feeds when he manually looks at logs.

In conjunction with that feature a new `notify-on-error` per-feed option might be added, which will allow to disable error-notifications for specific feeds. I would keep it enabled by default. 

```
https://gitlab.suse.de/security/secbox-image.atom
- template: /templates/default.tmpl
- notify-on-error: false
```

And if possible I would also add an extra email header to make email filtering easier. Something like 
```
X-RSS-Error: https://www.elastic.co/security-labs/feed
```

**Comment by skx** [comment]
That has been on my mind recently, so thank you for filing it.

So we have two modes of operation:

* Go through the list of feeds, process each, and then stop.
* Go through the list of feeds, process each, and then sleep, before starting again - in an endless loop.

At the moment it is possible to collect:

* Errors from processing a single feed.
* Errors from processing ALL the feeds.

The obvious thing to do would be to send an email of the errors, but the errors themselves are free-form, and of course the existing email template would be no good for displaying them.

We'd probably want a simple loop

     for each feed ..
        if errors
           "There were errors processing $feed"
           for each error
               * $error
           end
        endif
      end

I'm not averse to adding a new template, and using that for emails, but I suspect we'd then get into bikeshedding about the subject, the headers included, and the precise formatting.

I don't want to make this super-flexible, and allow overridden templates, because the complexity would rise a lot.  But I'd be willing to add something basic that would cover the cases like the ones above.

However my fear would be that this would get very noisy; I run in the deamon mode and so every fifteen minutes I expect I'd get the same error from the same flaky hosts.  In practice either:

* All feeds are up, reachable, and well-formed.
* One feed is unreachable (host down), or has malformed entries.

The second case is the case we want to notify on, but again in practice if a host is down it is down for a day, or two.  So every fifteen minutes for 48 hours, that's a lot of "Error with feed - host unreachable", or "DNS - unable to resolve host".     At that point you start to wonder about capping errors to "once per day", and if you do that you either need a database or state, to collect errors, or you risk dropping things.

There has to be a middle-ground between sending emails every time, not notifying at all unless the user looks at their (container) logs?  It does occur to me now that I could explicitly create an "errors.log" with the details above - if that grew it doesn't matter, and a user could use logcheck/logtail and a cronjob to send emails on failures.

Would using a logfile be the MVP?  Or is that still as bad as just writing to STDOUT?

**Comment by StayPirate** [comment]
I do run in daemon mode too and I agree with you, we should avoid to send too many notification errors (like every 15m) or it will become the next problem to address.

[Brainstorming mode on] I'm not sure if what I'm going to propose is doable, anyway.

#### Conditional template

```
From: {{env "FROM_EMAIL"}}
To: {{.To}}
{{- if .Error}}
  X-RSS-Error: {{.Feed}}
  Subject: [rss2emai] Fetching error for {{.Feed}}
{{else}}
  Subject: {{.Subject}}
  X-RSS-Link: {{.Link}}
  X-RSS-Feed: {{.Feed}}
  X-RSS-GUID: {{.RSSItem.GUID}}
  {{- if .RSSItem.Categories}}
  Keywords: {{.RSSItem.Categories}}
{{- end}}
{{- if env "RSS2EMAIL_INSTANCE_NAME"}}
  X-RSS-Instance: {{env "RSS2EMAIL_INSTANCE_NAME"}}
{{- end}}
{{- if .Tag}}
  X-RSS-Tags: {{.Tag}}
{{- end}}
Mime-Version: 1.0
Content-Transfer-Encoding: 8bit
Content-Base: {{.Link}}
Content-Type: text/html; charset=UTF-8

{{- if not .Error}}
  {{.Text}}
  {{.HTML}}
{{- end}}
```

#### Limit error notifications

To avoid too many error notifications or to fall into transient errors (temporary DNS error resolution, temporary connection reset, etc) a a minimum number of failed attempts should be set and only file an error notification after failed attempts reached that number. This number should also be customizable via an env var like `MIN_FAILURE_ATTEMPTS`.

Let's say that `MIN_FAILURE_ATTEMPTS` by default is set to 4 (1 per hour with standard daemon conf), the error-notification is only sent after 4 consecutive failed attempt. Once the notification is sent the failure counter for that feed is reset, so a second notification won't be sent before another hour. User will be free to manually set  `MIN_FAILURE_ATTEMPTS` to higher numbers if they want a small error-notifications ratio (eg. `MIN_FAILURE_ATTEMPTS=96` to get 1 per day).

The failure counter for the feed should of course be reset at each successful fetch attempt.

BTW the failure counters (one per feed) should be stored somewhere (the database?) so both daemon and cron modes could use it.

**Comment by StayPirate** [comment]
I missed an important point in my previous comment. Not providing the error's content to the users will give hard time for them if they want to understand what went wrong. The error's content could be sent in the email body with sth like the following lines:

```
[...headers...]
{{- if .Error}}
  {{.Error.Content}}
{{else}}
  {{.Text}}
  {{.HTML}}
{{- end}}
```

Moreover, I want to merge the idea of `MIN_FAILURE_ATTEMPTS` (previous comment) with `notify-on-error` (description). Instead of creating `notify-on-error` we could implement a per-feed option named `min_failure_attempts` which will take precedence over `MIN_FAILURE_ATTEMPTS` for a specific feed, and if it set to 0

```
https://gitlab.suse.de/security/secbox-image.atom
- template: /templates/default.tmpl
- notify-on-error: 0
```

then error notifications are disabled for that feed.

The same could maybe said for `MIN_FAILURE_ATTEMPTS`, if a user set it to `0` then rss2email won't send error notifications, expect for those feed that have the per-feed option  `notify-on-error` set to a value greater than 0.

**Comment by skx** [comment]
I've been thinking about this a fair bit as part of making the logging updates in #122, and I keep changing my mind.

It seems obvious that if we start talking about "Alert every X hours, or Y days" that we have to keep state.  That means we record errors somewhere and when the threshold in terms of number, of timeframe, has passed we then trigger a notification.

It also seems obvious that if we start reusing the existing template for _also_ showing errors it is going to get even more complex, and those poor users who have custom templates will start to see failures in the mostly likely case:

* We suddenly pass an array of errors to the template.
* But their template is local/custom, and won't have them.
* Which will trigger a error rendering.

The only way to cut down on the complexity and still show something useful that I can imagine is:

* If there were new items to notify ..
* Then _also_ show the errors from that specific run.

That means errors will become visible only if at least one feed has new entries, but that feels a bit horrid.

I think for the moment what I'd propose is the bare minimum:

* For every log message of level "ERROR".
   * Write it to a log file.

That allows a cronjob to be added:

```
file=.rss2email/error.log
if [ -e "$file" ] ; then
    cat "$file"
    rm "$file"
fi
```

I thought of making the deamon subcommand do that, once per day, but then we get into how to track "first run of the day", or "last run of the day", and it just feels like a horrible mess.

I'm open to the idea of adding a _new_ template "errors.tmpl", which could even be overridden.  But I think I'm against the idea of overloading the existing template to show errors.

I certainly don't want to show "errors every run", because that's just noisy, even if a feed is broken for only a few days.

The error.log can be expaned in the future, but it solves the immediate problem:

* There is a log of errors.
* This can be shown to the user, if they want to make that happen.

Perhaps the solution is a "errors" sub-command to show the errors?  Or is that just another way of avoiding responsibility?  I'm genuinely unsure!

**Comment by StayPirate** [comment]
1. I fully understand you point of view on avoiding to mess up existing templates, and I think you are right.
2. `error.log`, TBH this isn't something that really excites me. Logging is going to be done the right way via #122 and IMHO introducing `error.log` is not coherent.
3. Having too many error notifications should be avoided if possible.

Regarding point number 3, there is [another tool](https://changedetection.io/) (I'm using) that should already have faced this point. With it, I receive a dedicated email notification in case the tool encounters a fetching error. What _I think the tools does_ is that it saves the encountered errors and refrain to send more error-notifications if the same one keeps occurring. At least until the first successful fetch.
This could be a reasonable way for r2e too, what do you think? Of course, the tools should keep tracks of errors and related contents, until cleared (first next successful fetch).

```
Example

Fetch feed1 -> Error A -> Send error-notification for Error A
Fetch feed1 -> Error A -> Do nothing
Fetch feed1 -> Error B -> Send error-notification for Error B
Fetch feed1 -> Error A -> Do nothing
Fetch feed1 -> Error B -> Do nothing
Fetch feed1 -> Success -> Send emails if new items -> Clear Error A, Error B
Fetch feed1 -> Error A -> Send error-notification for Error A
Fetch feed1 -> Success -> Send emails if new items -> Clear Error A
[...]
You got the point :)
```

Point 1, you could add a dedicated template for errors and default to it when r2e needs to send out error-notifications. That should leave current and custom template safe.
