### ISSUE TITLE
Put feed.Title into the From: address?

### ISSUE THREAD

**Issue by DaleFarnsworth** [skx/rss2email#16]
I'm using the below patch so that my feed emails have the title of the feed in the sender address. If the passed sender address contains the string "{{FeedTitle}}", that string is replaced by the actual feed title.  Something like:
  rss2email cron -from="{{FeedTitle}} <email@mydomain.com>" email@mydomain.com
I'm happy with the result, but not sure the UI is the best.

```
diff --git a/cron_cmd.go b/cron_cmd.go
index 08755b1..f7b48c6 100644
--- a/cron_cmd.go
+++ b/cron_cmd.go
@@ -70,6 +70,8 @@ func (p *cronCmd) ProcessURL(input string) error {
                fmt.Printf("\tFound %d entries\n", len(feed.Items))
        }
 
+       fromAddr := strings.Replace(p.fromAddr, "{{FeedTitle}}", "\"" + feed.Title + "\"", 1)
+
        // For each entry in the feed ..
        for _, i := range feed.Items {
 
@@ -102,7 +104,7 @@ func (p *cronCmd) ProcessURL(input string) error {
                                text := html2text.HTML2Text(content)
 
                                // Send the mail
-                               err := SendMail(input, p.fromAddr, p.emails, i.Title, i.Link, text, content)
+                               err := SendMail(input, fromAddr, p.emails, i.Title, i.Link, text, content)
                                if err != nil {
                                        return err
                                }
```

**Comment by skx** [comment]
(Patch broken, but I see it in your fork.  No worries there.)

I'm less keen on this because I think the more natural approach would be to allow:

     $ rss2email cron --prefix="$TITLE" [options] steve@example.com

That way I could setup the default `--prefix` argument to be `[rss2email] ` allowing my mail filters to work as-is.  The only downside is that using `$` makes this a pain from a shell-escaping point of view.

Of course when I start thinking further I wonder if we should just allow the email template to be more customizable, loaded from a config file and then suddenly the change becomes more significant.   (For example that would mean the new email-sender flag is pointless.)

I'll sleep on it, but I think the sender's email address a bit of a bad UI overload, and that --prefix would be a good middle-ground.   Would that suit you too?  If so then the next thing to argue about would be the kind of things that could be inserted, I can imagine allowing more options/expansions but then it gets a bit messier again:

* $FEED.TITLE
* $ITEM.TITLE
* $ITEM.LINK  ?  PERMALINK?  URL?  Similar?
* $ITEM.AUTHOR
* ..?

I guess if it was as flexible as that even `--prefix` might be badly-named, instead we could use the following, to match the current behaviour:

     --subject="[rss2email] $ITEM.TITLE"

Or on your case:

     --subject="$FEED.TITLE $ITEM.TITLE"

**Comment by skx** [comment]
**NOTE**: There are already some X-headers in the email headers.  They're good for filtering, but not so flexible.

**Comment by skx** [comment]
Pull-request submitted as #17, @DaleFarnsworth let me know if that could work for you?

**Comment by DaleFarnsworth** [comment]
It' doesn't work for me yet, because I really want the feed title to appear as the name of the sender, i.e. in the From: line of the email.  It would work if you implemented the same mechanism for the from address, like:

    --from="#{FEED.TITLE} foo@bar.com"

BTW, I'm prototyping an implementation that exposes 3 template files: the email header, the text part, and the html part.  I'll just expose the variable substitution provided by text/template.  It provides maximum configurability, but may be too much for the user.  I'm close to finishing the first pass, but it's a substantial enough change that I'll want to review/revise it for a while.

**Comment by skx** [comment]
I'll update to allow the same thing for the From: header.

**Comment by skx** [comment]
Best approach seems to be to allow the whole template to be modified, which allows:

* Setting the feed-title in the email From: header
* Allow changing the sender
* Allows removing the `[rss2email]` prefix
* Allows adding more headers, etc.
