### ISSUE TITLE
Relative image path

### ISSUE THREAD

**Issue by gonejack** [skx/rss2email#56]
Hi, I got a feed using relative image references within it's HTML and Email clients cannot show images:

```https://www.williamlong.info/feed/```

**Comment by skx** [comment]
I think in that case you've got a broken feed, and there is little I could do about it :/

I did consider adding the ability to filter/rewrite/modify entries, but to make that flexible enough to fix things like this would be very hard.   I think a better approach is to ask authors to update their feeds to be valid.

**Comment by skx** [comment]
* https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.williamlong.info%2Ffeed%2F
   * column 3: description should not contain relative URL references: /upload/6391_1.jpg (5 occurrences

**Comment by skx** [comment]
Let me think about it for a few days, because I get the feeling that I should be making more changes to the config file.  e.g:

       https://example.com/feed.xml { 
          comment: "This is a comment"
          fix-relative: true
       }
       
Or similar.  Maybe YAML/JSON.

That way this stuff can be enabled on a per-feed basis, I don't like the idea of changing feeds silently - because I worry that it will break code inside `<pre>` sections, etc.  There's also more to fix, potentially such as `a href`, `frame src`, CSS includes, etc.

It all depends on how comprehensive you want to be.

**Comment by gonejack** [comment]
I recommend silently changing.

If there should be a config for this behavior, `dont-fix-relative` will be more friendly to most users.

**Comment by skx** [comment]
* If you submit a merge-request I will apply it.
* I __do__ want to change the config-file, but I'll leave that for the next release.
* I'm not so keen on silently fixing, because I worry it will break, but for the moment I will allow it.
