### ISSUE TITLE
FR: Allow for per-feed email addresses

### ISSUE THREAD

**Issue by avm99963** [skx/rss2email#73]
This program is currently designed so the email addresses are set when the cron or daemon commands are called. Anyways, I think it would be nice to redesign it in a way that allows different feeds to notify different email addresses, what do you think?

The easiest way to do this is to add a feed option which allows setting email addresses and which behaves like the template option (if it isn't set, then the default emails are used), although it might not be the best solution.

---

As a side note: thank you very much for developing this! :)) Now that Feedburner is deprecating email notifications, I started using your program via Docker and it's working great as a replacement! I love that it's very lightweight (go is awesome hehe).

I'll leave the template I created and use so the notifications are similar to the ones by Feedburner: https://gist.github.com/avm99963/14f81a255c6f8192c7cb420bfd86fd21

Screenshot of how emails look like:

![Screen Shot 2021-07-09 at 12 46 10](https://user-images.githubusercontent.com/682310/125066955-e6bf5a00-e0b3-11eb-96f3-6fc89a6264d9.png)

**Comment by avm99963** [comment]
Also, I forgot to mention that in case we agree to move this forward, I would be willing to code this and submit a PR!

**Comment by skx** [comment]
> This program is currently designed so the email addresses are set when the cron or daemon commands are called. Anyways, I think it would be nice to redesign it in a way that allows different feeds to notify different email addresses, what do you think?

I think that's a great suggestion.

> The easiest way to do this is to add a feed option which allows setting email addresses and which behaves like the template option (if it isn't set, then the default emails are used)

Agreed.

> Also, I forgot to mention that in case we agree to move this forward, I would be willing to code this and submit a PR!

If you want to have a stab at it then please feel free, otherwise I'm happy to make the necessary changes myself :)

I guess the hardest part will be deciding on the configuration.  I'd suggest:

```
      https://example.com/feed/path/here
       - notify: user@example.com, user2@example.net
```

(Then we can pretend in the future that `notify` might allow HTTP-posts to a webhook as well as just an email notification.)

> As a side note: thank you very much for developing this! :)) 

I'm glad it is useful to people :)

I wrote it because I wanted to get rid of all the python libraries I had installed on my shell box, which were only included as dependencies for [r2e](https://wiki.archlinux.org/title/Rss2email).

But over time people have been giving me ideas, and pull-requests, so it's got a bit nicer and better for everyone.

**Comment by avm99963** [comment]
> If you want to have a stab at it then please feel free, otherwise I'm happy to make the necessary changes myself :)
> 
> I guess the hardest part will be deciding on the configuration. I'd suggest:
> 
> ```
>       https://example.com/feed/path/here
>        - notify: user@example.com, user2@example.net
> ```
> 
> (Then we can pretend in the future that `notify` might allow HTTP-posts to a webhook as well as just an email notification.)

That seems right to me, I'll look into submitting a PR next week!

Again, thanks! :)

**Comment by avm99963** [comment]
Apologies for taking so long!
