### ISSUE TITLE
Returning expired or invalid certificate on all feed

### ISSUE THREAD

**Issue by tiagoprn** [skx/rss2email#74]
Hello, and congrats for the project! 

I have compiled rss2email from source using the official go binaries on a raspberry 4 here (using raspbian buster). 

When I run the command in daemon mode (when finished I plan to create systemd service and timer to automate it), I get a error like that on all my feeds: 

```
error processing https://thevaluable.dev/index.xml - x509: certificate has expired or is not yet valid: current time 2021-07-28T08:50:27-03:00 is after 2021-07-04T05:01:27Z
```

Can you help me on what I can do to fix that? (or maybe just ignore the certificate errors at all) 

Thanks you in advance!

**Comment by skx** [comment]
So you're saying that __all__ feeds you poll are reporting SSL errors, relating to expiration?

That sounds surprising, certainly the site you link to shows no error here.

Ignoring SSL errors, in general, is a bad idea.  I would suspect you could investigate by seeing if you can reproduce the error with other tools.  For example if you login to your PI can you run:

         wget https://thevaluable.dev/

or

         curl https://thevaluable.dev/

If they show the same error then the issue is obviously outside the scope of this project.  I would __guess__ the problem is that your system has the wrong date/time set.  You could look at fixing that to see if it helps.  To see the current setup run `date`.  If the date/time is obviously wrong then look at NTP to fix it.

**Comment by tiagoprn** [comment]
That makes absolute sense @skx. Especially due to raspberry not having a real time clock, I guess the problem's root is there. I will check if ntp is running and correctly configured, thank you for the quick response! :smile:

**Comment by skx** [comment]
Did you ever check up on this?
