### ISSUE TITLE
Multiple feeds.txt files

### ISSUE THREAD

**Issue by StayPirate** [skx/rss2email#92]
It would be nice to have feed addresses managed in multiple files. What I'm currently thinking is replacing `feeds.txt` with a `feed.d` folder, to be used in the following way:
```
feed.d
├── blog.feed
├── security-advisory.feed
└── news.feed
```
Do you like the idea?

Feed files should be processed in alphabetic order, so users would be able to use `10-blog.feed`, `20-news.feed`. And to avoid breaking compatibility with current `rss2email` version, priority to `feeds.txt` should be granted. IOW: if `feeds.txt` exists it should be used otherwise `feed.d`.

**Comment by skx** [comment]
It's not a bad idea, but I'm a little reluctant to handle it because the configuration handling we use at the moment is already more complex than I'd like.

When the project was launched it used to read `~/.rss2email/feeds`, now it reads `feeds.txt` and there is migration code in-place to convert from the old to the new.  

This migration, as well as the use of `~/.rss2email/state/xxx` will be dropped in the 3.x release, as noted in #86.

Right now I'd say that adding more complexity to the config is not desirable, and perhaps the best way would be for the user to manage the directory -> single file transition themselves.

For example create `~/.rss2email/feed.d/`, and then create `~/.rss2email/Makefile`:

```
default: $(wildcard feed.d/*.txt)
	cat feed.d/*.txt > feeds
```

Then you can run `make` whenever you add/edit/delete an input file beneath the `~/.rss2email/fee.d/` directory.

**Comment by StayPirate** [comment]
> It's not a bad idea, but I'm a little reluctant to handle it because the configuration handling we use at the moment is already more complex than I'd like.

Understood, maybe in the future this can be reconsiderated.

> For example create `~/.rss2email/feed.d/`, and then create `~/.rss2email/Makefile`:
> 
> ```
> default: $(wildcard feed.d/*.txt)
> 	cat feed.d/*.txt > feeds
> ```
> 
> Then you can run `make` whenever you add/edit/delete an input file beneath the `~/.rss2email/fee.d/` directory.

I don't like the idea of having to run `make` or whatever else command every time after I update my feeds. My plan is to manage the feeds only via `git` and having in place CI/CD to do the rest. Maybe a pre-commit git hook can find its way here, but I think a less-complex and more elegant, solution should be preferred.

I close this issue for now, if you want to implement that after v3.x is out you can re-open it. Thanks for your feedback.
